module MyEgo {
    requires javafx.controls;
    requires javafx.fxml;
    requires java.sql;
    requires spring.boot.autoconfigure;
    requires spring.boot;
    requires spring.context;
    requires spring.beans;
    requires spring.core;
    requires spring.data.jpa;
    requires spring.jdbc;
    requires spring.tx;
    requires jakarta.persistence;
    requires org.hibernate.orm.core;
    requires spring.security.crypto;
    requires spring.data.commons;
    requires spring.boot.starter;


    exports br.com.myegoo.app.myego;
    opens br.com.myegoo.app.myego to javafx.controls,spring.core, javafx.fxml, spring.beans, spring.context, spring.boot, spring.boot.autoconfigure;
    exports br.com.myegoo.app.myego.controller;
    opens br.com.myegoo.app.myego.controller to javafx.controls, javafx.fxml, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.model;
    opens br.com.myegoo.app.myego.model to jakarta.persistence, org.hibernate.orm.core, spring.beans, spring.core, javafx.controls, javafx.fxml, spring.boot, spring.boot.autoconfigure, spring.context;
    exports br.com.myegoo.app.myego.service to spring.beans, spring.core;
    opens br.com.myegoo.app.myego.service;
    exports br.com.myegoo.app.myego.repository to spring.beans, spring.core;
    opens br.com.myegoo.app.myego.repository;
    exports br.com.myegoo.app.myego.utils to jakarta.persistence, org.hibernate.orm.core, spring.beans, spring.core, javafx.controls, javafx.fxml, spring.boot, spring.boot.autoconfigure, spring.context;
    opens br.com.myegoo.app.myego.utils to jakarta.persistence, org.hibernate.orm.core, spring.beans, spring.core, javafx.controls, javafx.fxml, spring.boot, spring.boot.autoconfigure, spring.context;
    exports br.com.myegoo.app.myego.model.tarefa;
    opens br.com.myegoo.app.myego.model.tarefa to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.model.estudo;
    opens br.com.myegoo.app.myego.model.estudo to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.tarefa to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.tarefa to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.login to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.login to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.estudo to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.estudo to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.service.login to spring.beans, spring.core;
    opens br.com.myegoo.app.myego.service.login;
    exports br.com.myegoo.app.myego.service.estudo to spring.beans, spring.core;
    opens br.com.myegoo.app.myego.service.estudo;
    exports br.com.myegoo.app.myego.model.projetos;
    opens br.com.myegoo.app.myego.model.projetos to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.service.projeto to spring.beans, spring.core;
    opens br.com.myegoo.app.myego.service.projeto;
    exports br.com.myegoo.app.myego.service.meta to spring.beans, spring.core;
    opens br.com.myegoo.app.myego.service.meta;
    exports br.com.myegoo.app.myego.model.meta;
    opens br.com.myegoo.app.myego.model.meta to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.configuration to spring.beans, spring.core;
    opens br.com.myegoo.app.myego.configuration;
    exports br.com.myegoo.app.myego.model.financas;
    opens br.com.myegoo.app.myego.model.financas to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.model.treino;
    opens br.com.myegoo.app.myego.model.treino to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.projeto to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.projeto to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.habitos to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.habitos to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.financas to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.financas to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.metas to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.metas to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    exports br.com.myegoo.app.myego.utils.treino to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;
    opens br.com.myegoo.app.myego.utils.treino to jakarta.persistence, javafx.controls, javafx.fxml, org.hibernate.orm.core, spring.beans, spring.boot, spring.boot.autoconfigure, spring.context, spring.core;

}